#!/bin/env python

#### configuration file ####
configfile: "config/config_DS_initial.yaml" 
configfile: "config/config_DS.yaml"

include: "workflow/rules/common.smk"

rule all:
    input:
        lambda w: allInput(config["method"], config["build"], config["sample"]),

include: "workflow/rules/fastqc.smk"
include: "workflow/rules/zipping_samples.smk"
include: "workflow/rules/genome_download.smk"
include: "workflow/rules/genome_build.smk"
include: "workflow/rules/genome_indexing.smk"
include: "workflow/rules/genome_idx2ron.smk"
include: "workflow/rules/adaptor_handling.smk"
include: "workflow/rules/align.smk"
include: "workflow/rules/bam2bed.smk"
include: "workflow/rules/sort_filter.smk"
include: "workflow/rules/length_distribution.smk"
include: "workflow/rules/sep_strands.smk"
include: "workflow/rules/reposition.smk"
include: "workflow/rules/bed2fasta.smk"
include: "workflow/rules/dinucleotide_table.smk"
include: "workflow/rules/filtbyMotifs.smk"
include: "workflow/rules/genomecov.smk"
include: "workflow/rules/bedGraphToBigWig.smk"
include: "workflow/rules/simulation.smk"