method: XR

sample: 
  - "HXA64A1_ATCACG_sub10k"

layout:
  - "single-end"

adaptor_se: "-a TGGAATTCTCGGGTGCCAAGGAACTCCAGTNNNNNNACGATCTCGTATGCCGTCTTCTGCTTG"

adaptor_pe: "-a TGGAATTCTCGGGTGCCAAGGAACTCCAGTNNNNNNACGATCTCGTATGCCGTCTTCTGCTTG -A TGGAATTCTCGGGTGCCAAGGAACTCCAGTNNNNNNACGATCTCGTATGCCGTCTTCTGCTTG"

cutadapt_se: ""

cutadapt_pe: ""

bowtie2: ""

samtools_q_trim_se: "-q 20"

samtools_q_trim_pe: "-q 20 -bf 0x2"

filter: "'^chr([1-9]|1[0-9]|2[0-2]|X)'"

# Genome parameters 

build: "GRCh37"

species: "homo_sapiens"

datatype: "dna"

release: "102"

#######
  


 
  

 
